local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.WILLARSWORD = "Gilded Cutlass"
STRINGS.NAMES.MONKEYDISGUISE = "Cheeky Disguise"
STRINGS.NAMES.WILLARCROWN = "Noble Crown"
STRINGS.NAMES.WILLARCROWN_RUINS = "Usurpers Crown"
STRINGS.NAMES.FARMERMONKEYPOD = "Farmer Pod"
STRINGS.NAMES.FARMER_MONKEY = "Farmer Monkey"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILLARSWORD = "Well it's definitely an upgrade."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYDISGUISE = "They'll be none the wiser, I'm sure."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILLARCROWN = "The bananas gives it its power. That's just science."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILLARCROWN_RUINS = "Fit for primate royalty!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARMERMONKEYPOD = {
    GENERIC = "Home to hard work.",
    BURNT = "Home to burnt aspirations."
}
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARMER_MONKEY = "He's quite the helping hand!"